/* eslint-disable react-hooks/set-state-in-effect, react-hooks/purity, react-hooks/exhaustive-deps */
"use client";
import {FormEvent,KeyboardEvent,useCallback,useEffect,useMemo,useRef,useState} from "react";
import {applyCommand,commandById,commands,initialDevice,modeNames,prepare,prompt,seededOrder,validate,type DeviceState} from "@/lib/engine.ts";
import {due,nextDue,schedule,score,type Outcome,type Review} from "@/lib/scheduler.ts";

type Screen="home"|"round"|"report";
interface CommandProgress{attempts:number;correct:number;firstTry:number;lastError:string|null;review?:Review}
interface Progress{bestScore:number|null;bestCombo:number;rounds:number;commands:Record<string,CommandProgress>;muted:boolean;reducedMotion:boolean}
interface Round{score:number;submissions:number;resolved:number;firstTry:number;combo:number;bestCombo:number;times:number[];errors:Record<string,number>;reviewIds:string[];missed:string[]}
interface Report{round:Round;full:boolean;personalBest:boolean;previousBest:number|null}
const blankProgress=():Progress=>({bestScore:null,bestCombo:0,rounds:0,commands:{},muted:false,reducedMotion:false});
const blankRound=():Round=>({score:0,submissions:0,resolved:0,firstTry:0,combo:0,bestCombo:0,times:[],errors:{},reviewIds:[],missed:[]});
const uniq=(a:string[])=>[...new Set(a)];
const errorNames:Record<string,string>={EMPTY:"Empty command",TOO_LONG:"Input too long",WRONG_MODE:"Wrong CLI mode",MISSING_KEYWORD:"Missing keyword",MISSING_ARGUMENT:"Missing argument",KEYWORD_ORDER:"Keyword order",EXTRA_INPUT:"Extra input",INVALID_IPV4:"Invalid IPv4 address",INVALID_MASK:"Invalid subnet mask",MASK_KIND:"Wrong mask type",INVALID_INTERFACE:"Invalid interface",WRONG_VALUE:"Wrong objective value",VERIFY_NOT_CONFIGURE:"Verification instead of configuration",CONFIGURE_NOT_VERIFY:"Configuration instead of verification",WRONG_OBJECTIVE:"Wrong objective",UNSUPPORTED:"Unsupported command"};
const median=(a:number[])=>{if(!a.length)return null;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2;};
const pct=(n:number)=>`${Math.round(n*100)}%`;
const storageKey="cli-rush-progress-v1";

export default function Home(){
  const [screen,setScreen]=useState<Screen>("home"),[progress,setProgress]=useState<Progress>(blankProgress),[round,setRound]=useState<Round>(blankRound),[report,setReport]=useState<Report|null>(null);
  const progressRef=useRef(progress),roundRef=useRef(round),finishing=useRef(false),retried=useRef(new Set<string>());
  const [queue,setQueue]=useState(()=>seededOrder(1)),[cursor,setCursor]=useState(0),[device,setDevice]=useState<DeviceState>(initialDevice),[time,setTime]=useState(60000),[paused,setPaused]=useState(false);
  const [input,setInput]=useState(""),[history,setHistory]=useState<string[]>([]),[historyAt,setHistoryAt]=useState(-1),[lines,setLines]=useState<string[]>([]),[attempts,setAttempts]=useState(0),[revealed,setRevealed]=useState(false),[startedAt,setStartedAt]=useState(0),[advancing,setAdvancing]=useState(false);
  const [feedback,setFeedback]=useState({tone:"neutral",title:"Terminal ready",message:"Read the objective, check the prompt and enter the command."});
  const inputRef=useRef<HTMLInputElement>(null),logRef=useRef<HTMLDivElement>(null);
  const item=useMemo(()=>commandById.get(queue[cursor%queue.length])??commands[0],[queue,cursor]);
  const save=(p:Progress)=>{progressRef.current=p;setProgress(p);try{localStorage.setItem(storageKey,JSON.stringify(p));}catch{}};
  const setRoundBoth=(r:Round)=>{roundRef.current=r;setRound(r);};
  useEffect(()=>{try{const raw=localStorage.getItem(storageKey);if(raw){const p=JSON.parse(raw) as Progress;if(p&&p.commands){progressRef.current=p;setProgress(p);}}}catch{}},[]);
  useEffect(()=>{if(screen!=="round")return;setDevice(s=>prepare(s,item));setAttempts(0);setRevealed(false);setHistory([]);setHistoryAt(-1);setStartedAt(performance.now());setAdvancing(false);setTimeout(()=>inputRef.current?.focus(),0);},[cursor,item,screen]);
  useEffect(()=>{logRef.current?.scrollTo({top:logRef.current.scrollHeight});},[lines]);
  useEffect(()=>{if(screen!=="round"||paused)return;const id=setInterval(()=>setTime(v=>Math.max(0,v-100)),100);return()=>clearInterval(id);},[screen,paused]);

  const tone=(good:boolean)=>{if(progressRef.current.muted)return;try{const Ctx=window.AudioContext;const ctx=new Ctx(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=good?740:190;g.gain.setValueAtTime(.04,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.08);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.08);o.onended=()=>void ctx.close();}catch{}};
  const updateCommand=(id:string,count:number,first:boolean,lastError:string|null,outcome:Outcome)=>{const p=progressRef.current,old=p.commands[id];save({...p,commands:{...p.commands,[id]:{attempts:(old?.attempts??0)+count,correct:(old?.correct??0)+1,firstTry:(old?.firstTry??0)+(first?1:0),lastError,review:schedule(old?.review,outcome,Date.now())}}});};
  const failUnresolved=(id:string,count:number,lastError:string|null)=>{if(!count)return;const p=progressRef.current,old=p.commands[id];save({...p,commands:{...p.commands,[id]:{attempts:(old?.attempts??0)+count,correct:old?.correct??0,firstTry:old?.firstTry??0,lastError,review:schedule(old?.review,"failed",Date.now())}}});};

  const finish=useCallback((full:boolean)=>{if(finishing.current||screen!=="round")return;finishing.current=true;let r=roundRef.current;if(attempts){const last=Object.entries(r.errors).sort((a,b)=>b[1]-a[1])[0]?.[0]??null;failUnresolved(item.id,attempts,last);r={...r,reviewIds:uniq([...r.reviewIds,item.id]),missed:uniq([...r.missed,item.id])};roundRef.current=r;}const p=progressRef.current,personalBest=full&&(p.bestScore===null||r.score>p.bestScore);save({...p,rounds:p.rounds+(full?1:0),bestScore:personalBest?r.score:p.bestScore,bestCombo:Math.max(p.bestCombo,r.bestCombo)});setReport({round:r,full,personalBest,previousBest:p.bestScore});setPaused(false);setScreen("report");},[attempts,item.id,screen]);
  useEffect(()=>{if(screen==="round"&&time===0)finish(true);},[time,screen,finish]);

  const start=()=>{const r=blankRound();setRoundBoth(r);setQueue(seededOrder(progressRef.current.rounds+1));setCursor(0);setDevice(initialDevice());setTime(60000);setPaused(false);setInput("");setLines(["CLI RUSH local simulator // IOS XE draft pack","Memory mode: full canonical commands required"]);setFeedback({tone:"neutral",title:"Round started",message:"Check the objective and current CLI prompt."});setReport(null);finishing.current=false;retried.current.clear();setScreen("round");};
  const submit=(e:FormEvent)=>{e.preventDefault();if(paused||advancing||!time)return;const result=validate(input,device.mode,item.id);if(!result.input){if(!result.ok)setFeedback({tone:"error",title:"Nothing entered",message:result.message});return;}const p=prompt(device);setHistory(h=>[...h,result.input].slice(-20));setHistoryAt(-1);
    if(!result.ok){const n=attempts+1,code=result.code;const r={...roundRef.current,submissions:roundRef.current.submissions+1,combo:0,errors:{...roundRef.current.errors,[code]:(roundRef.current.errors[code]??0)+1},reviewIds:uniq([...roundRef.current.reviewIds,item.id]),missed:uniq([...roundRef.current.missed,item.id])};setRoundBoth(r);setAttempts(n);setLines(l=>[...l,`${p} ${result.input}`,`% ${result.message}`].slice(-60));setInput("");tone(false);if(!retried.current.has(item.id)){retried.current.add(item.id);setQueue(q=>{const n=[...q];n.splice(Math.min(n.length,cursor+4),0,item.id);return n;});}if(n>=3){setRevealed(true);setFeedback({tone:"error",title:`${errorNames[code]} · answer revealed`,message:`Type the canonical command to continue: ${item.canonical}`});}else setFeedback({tone:"error",title:errorNames[code]??"Command error",message:n===2?`${result.message} Structure starts with “${item.canonical.split(" ")[0]}”.`:result.message});setTimeout(()=>inputRef.current?.focus(),0);return;}
    const count=attempts+1,first=count===1&&!revealed,combo=first?roundRef.current.combo+1:0,response=Math.max(0,performance.now()-startedAt),points=score(item.difficulty,count,response,combo,revealed),sim=applyCommand(device,item);const last=attempts?Object.entries(roundRef.current.errors).sort((a,b)=>b[1]-a[1])[0]?.[0]??null:null;const r={...roundRef.current,score:roundRef.current.score+points,submissions:roundRef.current.submissions+1,resolved:roundRef.current.resolved+1,firstTry:roundRef.current.firstTry+(first?1:0),combo,bestCombo:Math.max(roundRef.current.bestCombo,combo),times:[...roundRef.current.times,response],reviewIds:uniq([...roundRef.current.reviewIds,item.id])};setRoundBoth(r);updateCommand(item.id,count,first,last,revealed?"revealed":first?"firstTry":"retry");setDevice(sim.state);setLines(l=>[...l,`${p} ${result.input}`,...sim.output,`✓ +${points} points${first?` · ${combo}x combination`:" · assisted recall"}`].slice(-60));setFeedback({tone:"success",title:first?"Command accepted":revealed?"Correctly retyped":"Correct after feedback",message:first?`${item.explanation} +${points} points.`:"This command is scheduled for another unassisted review."});setInput("");setAdvancing(true);tone(true);setTimeout(()=>setCursor(x=>x+1),progressRef.current.reducedMotion?0:120);
  };
  const historyKeys=(e:KeyboardEvent<HTMLInputElement>)=>{if(e.key==="ArrowUp"){e.preventDefault();if(!history.length)return;const n=historyAt<0?history.length-1:Math.max(0,historyAt-1);setHistoryAt(n);setInput(history[n]);}if(e.key==="ArrowDown"){e.preventDefault();const n=historyAt+1;if(historyAt<0||n>=history.length){setHistoryAt(-1);setInput("");}else{setHistoryAt(n);setInput(history[n]);}}};
  const reviews=Object.fromEntries(Object.entries(progress.commands).filter(([,x])=>x.review).map(([id,x])=>[id,x.review!]));const dueCount=due(reviews,Date.now()).length,next=nextDue(reviews);
  const settings=(key:"muted"|"reducedMotion")=>save({...progressRef.current,[key]:!progressRef.current[key]});
  const common=report?Object.entries(report.round.errors).sort((a,b)=>b[1]-a[1])[0]?.[0]??null:null,med=report?median(report.round.times):null;

  return <main className={`shell ${progress.reducedMotion?"reduced":""}`}><div className="grid-bg"/>
    <header><div className="brand"><b>CR</b><span><strong>CLI RUSH</strong><small>Network Command Arena</small></span></div><div className="controls"><span className="saved">● Saved locally</span><button onClick={()=>settings("muted")}>{progress.muted?"Sound off":"Sound on"}</button><button onClick={()=>settings("reducedMotion")}>{progress.reducedMotion?"Motion reduced":"Reduce motion"}</button></div></header>
    {screen==="home"&&<section className="home"><div className="hero"><p className="eyebrow">IOS XE · MEMORY MODE</p><h1>Think in commands.<em>Move at line speed.</em></h1><p className="lead">Recall Cisco-style commands from memory, enter them in the right CLI context and get precise feedback before the next objective lands.</p><button className="primary" onClick={start}>Start 60s Command Rush <kbd>Enter</kbd></button><dl><div><dt>Best score</dt><dd>{progress.bestScore??"—"}</dd></div><div><dt>Best combination</dt><dd>{progress.bestCombo?`${progress.bestCombo}x`:"—"}</dd></div><div><dt>Due reviews</dt><dd>{dueCount}</dd></div></dl></div><aside><div className="aside-head">ROUND BRIEFING <b>LIVE</b></div><div className="demo"><small>OBJECTIVE</small><p>Display a concise summary of interface addresses and status.</p><code><i>R1#</i> show ip interface brief</code><span>✓ Command accepted <b>+115</b></span></div><div className="facts"><div><b>60</b><span>seconds</span></div><div><b>5</b><span>CLI modes</span></div><div><b>{commands.length}</b><span>commands</span></div></div><div className="queue"><b>↻</b><span><strong>Recall queue</strong><small>{next?next<=Date.now()?"Reviews due now":`Next review in ${Math.ceil((next-Date.now())/60000)} min`:"No reviews scheduled"}</small></span><em>{dueCount}</em></div></aside></section>}
    {screen==="round"&&<section className="game"><div className="game-top"><span>COMMAND RUSH<br/><b>ROUND {progress.rounds+1}</b></span><div className={`clock ${time<=10000?"danger":""}`}><small>TIME</small><b>{String(Math.ceil(time/1000)).padStart(2,"0")}</b></div><div className="metrics"><span>SCORE<b>{round.score}</b></span><span>COMBINATION<b>{round.combo}x</b></span></div></div><div className="track"><i style={{width:`${time/600}%`}}/></div><div className="objective"><p>{item.topic} · DIFFICULTY {item.difficulty} · {modeNames[item.mode]}</p><small>OPERATIONAL OBJECTIVE</small><h2>{paused?"Objective hidden while paused":item.objective}</h2></div><div className="terminal"><div className="terminal-head"><span>● ● ● &nbsp; {device.hostname}{" // "}CONSOLE</span><button onClick={()=>setPaused(true)} disabled={paused}>Pause</button></div>{paused?<div className="pause"><b>Ⅱ</b><h2>Round paused</h2><p>The clock is stopped and the objective is hidden.</p><div><button className="primary small" onClick={()=>setPaused(false)}>Resume round</button><button className="secondary" onClick={()=>finish(false)}>End round</button></div></div>:<><div className="log" ref={logRef} role="log">{lines.map((line,i)=><div key={`${i}-${line}`}>{line}</div>)}</div><form onSubmit={submit}><label className="sr" htmlFor="command">Command input</label><span>{prompt(device)}</span><input id="command" ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={historyKeys} onPaste={e=>e.preventDefault()} autoComplete="off" autoCorrect="off" spellCheck={false} maxLength={256} disabled={advancing}/><button disabled={advancing}>Run</button></form></>}</div>{!paused&&<div className={`feedback ${feedback.tone}`} aria-live="polite"><b>{feedback.tone==="success"?"✓":feedback.tone==="error"?"!":"i"}</b><span><strong>{feedback.title}</strong><p>{feedback.message}</p></span>{revealed&&<code>{item.canonical}</code>}</div>}<p className="help">Enter submits · ↑/↓ command history · Paste is disabled in memory rounds</p></section>}
    {screen==="report"&&report&&<section className="report"><div className="report-title"><p className="eyebrow">ROUND REPORT</p><h1>{report.full?"Sixty seconds complete.":"Round ended early."}</h1><p>{report.personalBest?(report.previousBest===null?"First recorded full round. This is your baseline.":"New personal best recorded."):report.full?"Your result and review schedule are saved locally.":"Completed attempts were saved, but an early finish does not update your personal best."}</p></div><div className="final-score"><small>FINAL SCORE</small><b>{report.round.score}</b>{report.personalBest&&<em>PERSONAL BEST</em>}</div><div className="report-grid"><div><small>Commands resolved</small><b>{report.round.resolved}</b><span>{report.round.submissions} submissions</span></div><div><small>First-attempt accuracy</small><b>{pct(report.round.resolved?report.round.firstTry/report.round.resolved:0)}</b><span>{report.round.firstTry} clean recalls</span></div><div><small>Overall accuracy</small><b>{pct(report.round.submissions?report.round.resolved/report.round.submissions:0)}</b><span>Correct submissions</span></div><div><small>Median response</small><b>{med===null?"—":`${(med/1000).toFixed(1)}s`}</b><span>Resolved commands</span></div><div><small>Best combination</small><b>{report.round.bestCombo}x</b><span>First-try answers</span></div><div><small>Scheduled reviews</small><b>{uniq(report.round.reviewIds).length}</b><span>Saved locally</span></div></div><div className="report-detail"><div><small>MOST COMMON ERROR</small><b>{common?errorNames[common]:"No errors recorded"}</b><p>{common?"This is the clearest target for the next round.":"Delayed review will test whether this recall holds."}</p></div><div><small>RECOMMENDED NEXT ACTION</small><b>{report.round.missed.length?"Run another Command Rush":"Repeat after the review interval"}</b><p>{report.round.missed.length?"Missed commands are queued again and scheduled for later review.":"Accuracy is established; let spacing test retention."}</p></div></div><div className="report-actions"><button className="primary" onClick={start}>Run another 60s</button><button className="secondary" onClick={()=>setScreen("home")}>Return home</button></div></section>}
    <footer><span>Independent educational simulator · Not affiliated with or endorsed by Cisco</span><span>IOS XE learning pack v0.1 · Simulator-tested draft</span></footer>
  </main>;
}
