import type { CliMode, Command, CommandKind } from "./engine.ts";

type Row = [string, CliMode, string, string, string, CommandKind, (1 | 2 | 3)?];
const rows: Row[] = [
  ["user.show-clock","user","show clock","Display the device clock.","CLI and system","verification"],
  ["user.show-history","user","show history","Display recent commands.","CLI and system","verification"],
  ["user.ssh","user","ssh -l netadmin 192.0.2.10","Open an SSH session as netadmin.","Secure management","verification",2],
  ["user.logout","user","logout","Close the current EXEC session.","CLI navigation","navigation"],

  ["show.clock-detail","privileged","show clock detail","Display detailed clock and time-source status.","CLI and system","verification"],
  ["show.inventory","privileged","show inventory","Display installed hardware inventory.","Device verification","verification"],
  ["show.platform","privileged","show platform","Display platform component status.","Device verification","verification",2],
  ["show.license-summary","privileged","show license summary","Display a concise licence status summary.","Device verification","verification",2],
  ["show.boot","privileged","show boot","Display boot variables.","Configuration management","verification",2],
  ["show.flash","privileged","dir flash:","List files in flash storage.","Configuration management","verification"],
  ["show.filesystems","privileged","show file systems","Display available device file systems.","Configuration management","verification",2],
  ["show.archive","privileged","show archive","Display configuration archive status.","Configuration management","verification",2],
  ["show.users","privileged","show users","Display users connected to the device.","Secure management","verification"],
  ["show.sessions","privileged","show sessions","Display outbound management sessions.","Secure management","verification",2],
  ["show.ssh","privileged","show ssh","Display active SSH sessions.","Secure management","verification"],
  ["show.ip-ssh","privileged","show ip ssh","Display the SSH server configuration.","Secure management","verification"],
  ["show.login","privileged","show login","Display enhanced login blocking status.","Secure management","verification",2],
  ["show.logging","privileged","show logging","Display syslog configuration and buffered messages.","Monitoring services","verification"],
  ["show.ntp-status","privileged","show ntp status","Display NTP synchronisation status.","Monitoring services","verification"],
  ["show.ntp-associations","privileged","show ntp associations","Display NTP peers and reachability.","Monitoring services","verification",2],
  ["show.snmp","privileged","show snmp","Display SNMP engine statistics.","Monitoring services","verification",2],
  ["show.processes-cpu","privileged","show processes cpu sorted","Display processes sorted by CPU use.","Troubleshooting","verification",2],
  ["show.processes-memory","privileged","show processes memory sorted","Display processes sorted by memory use.","Troubleshooting","verification",2],
  ["show.environment","privileged","show environment all","Display environmental sensor state.","Troubleshooting","verification",2],
  ["show.ip-arp","privileged","show ip arp","Display the IPv4 ARP table.","Neighbour discovery","verification"],
  ["show.ip-interface","privileged","show ip interface GigabitEthernet0/1","Display IPv4 details for GigabitEthernet0/1.","Interface verification","verification",2],
  ["show.interface-counters","privileged","show interfaces counters errors","Display interface error counters.","Interface verification","verification",2],
  ["show.interface-status","privileged","show interfaces status","Display switch-port status.","Layer 2 switching","verification"],
  ["show.interface-switchport","privileged","show interfaces GigabitEthernet0/1 switchport","Display Layer 2 settings for GigabitEthernet0/1.","Layer 2 switching","verification",2],
  ["show.interfaces-trunk","privileged","show interfaces trunk","Display active trunk ports and allowed VLANs.","Layer 2 switching","verification"],
  ["show.mac-table","privileged","show mac address-table","Display the MAC address table.","Layer 2 switching","verification"],
  ["show.mac-dynamic","privileged","show mac address-table dynamic","Display dynamically learned MAC addresses.","Layer 2 switching","verification",2],
  ["show.spanning-tree","privileged","show spanning-tree","Display Spanning Tree state for all VLANs.","Spanning Tree","verification"],
  ["show.spanning-tree-vlan","privileged","show spanning-tree vlan 20","Display Spanning Tree state for VLAN 20.","Spanning Tree","verification",2],
  ["show.spanning-tree-root","privileged","show spanning-tree root","Display the root bridge for each VLAN.","Spanning Tree","verification",2],
  ["show.etherchannel-summary","privileged","show etherchannel summary","Display EtherChannel protocol and member status.","EtherChannel","verification"],
  ["show.etherchannel-portchannel","privileged","show etherchannel port-channel","Display detailed port-channel information.","EtherChannel","verification",2],
  ["show.lacp-neighbor","privileged","show lacp neighbor","Display LACP neighbours.","EtherChannel","verification",2],
  ["show.pagp-neighbor","privileged","show pagp neighbor","Display PAgP neighbours.","EtherChannel","verification",2],
  ["show.lldp-neighbors","privileged","show lldp neighbors","Display directly connected LLDP neighbours.","Neighbour discovery","verification"],
  ["show.cdp-detail","privileged","show cdp neighbors detail","Display detailed CDP neighbour information.","Neighbour discovery","verification",2],
  ["show.ip-protocols","privileged","show ip protocols","Display active IPv4 routing protocol settings.","Routing","verification"],
  ["show.ip-route-connected","privileged","show ip route connected","Display connected IPv4 routes.","Routing","verification"],
  ["show.ip-route-static","privileged","show ip route static","Display static IPv4 routes.","Routing","verification",2],
  ["show.ip-route-ospf","privileged","show ip route ospf","Display routes learned through OSPF.","OSPF","verification",2],
  ["show.ip-ospf","privileged","show ip ospf","Display OSPF process information.","OSPF","verification",2],
  ["show.ip-ospf-neighbor","privileged","show ip ospf neighbor","Display OSPF neighbour adjacencies.","OSPF","verification"],
  ["show.ip-ospf-interface-brief","privileged","show ip ospf interface brief","Display a concise OSPF interface summary.","OSPF","verification",2],
  ["show.ip-ospf-database","privileged","show ip ospf database","Display the OSPF link-state database.","OSPF","verification",3],
  ["show.ipv6-interface-brief","privileged","show ipv6 interface brief","Display a concise IPv6 interface summary.","IPv6","verification"],
  ["show.ipv6-route","privileged","show ipv6 route","Display the IPv6 routing table.","IPv6","verification"],
  ["show.ipv6-neighbors","privileged","show ipv6 neighbors","Display the IPv6 neighbour cache.","IPv6","verification",2],
  ["show.access-lists","privileged","show access-lists","Display all configured access lists.","Access control","verification"],
  ["show.ip-access-lists","privileged","show ip access-lists","Display configured IPv4 access lists.","Access control","verification"],
  ["show.ipv6-access-list","privileged","show ipv6 access-list","Display configured IPv6 access lists.","Access control","verification",2],
  ["show.dhcp-binding","privileged","show ip dhcp binding","Display IPv4 DHCP leases.","DHCP","verification"],
  ["show.dhcp-pool","privileged","show ip dhcp pool","Display DHCP pool utilisation.","DHCP","verification"],
  ["show.dhcp-conflict","privileged","show ip dhcp conflict","Display DHCP address conflicts.","DHCP","verification",2],
  ["show.nat-translations","privileged","show ip nat translations","Display active NAT translations.","NAT","verification"],
  ["show.nat-statistics","privileged","show ip nat statistics","Display NAT counters and interface roles.","NAT","verification",2],
  ["show.port-security","privileged","show port-security","Display port-security status.","Switch security","verification"],
  ["show.port-security-interface","privileged","show port-security interface GigabitEthernet0/1","Display port-security details for GigabitEthernet0/1.","Switch security","verification",2],
  ["show.dhcp-snooping","privileged","show ip dhcp snooping","Display DHCP snooping configuration.","Switch security","verification"],
  ["show.dhcp-snooping-binding","privileged","show ip dhcp snooping binding","Display trusted DHCP snooping bindings.","Switch security","verification",2],
  ["show.arp-inspection","privileged","show ip arp inspection","Display Dynamic ARP Inspection status.","Switch security","verification",2],
  ["show.hsrp-brief","privileged","show standby brief","Display a concise HSRP state summary.","First-hop redundancy","verification",2],
  ["verify.ping-source","privileged","ping 198.51.100.1 source 192.0.2.1","Test reachability using source address 192.0.2.1.","Troubleshooting","verification",2],
  ["verify.traceroute-source","privileged","traceroute 198.51.100.10 source 192.0.2.1","Trace a path using source address 192.0.2.1.","Troubleshooting","verification",3],
  ["config.erase-startup","privileged","erase startup-config","Erase the simulated startup configuration.","Configuration management","configuration",2],
  ["config.reload","privileged","reload","Reload the simulated device.","Configuration management","configuration",2],

  ["config.enable-secret","global","enable secret <secret-value>","Configure a supplied privileged EXEC secret in the simulator.","Secure management","configuration"],
  ["config.username","global","username netadmin privilege 15 secret <secret-value>","Create the fictional local netadmin account with a supplied secret.","Secure management","configuration",2],
  ["config.domain-name","global","ip domain-name lab.example","Configure the device domain name.","Secure management","configuration"],
  ["config.crypto-key","global","crypto key generate rsa modulus 2048","Generate a simulated 2048-bit RSA key.","Secure management","configuration",2],
  ["config.ssh-version","global","ip ssh version 2","Require SSH version 2.","Secure management","configuration"],
  ["config.login-block","global","login block-for 120 attempts 3 within 60","Block repeated failed login attempts.","Secure management","configuration",3],
  ["config.banner","global","banner motd #Authorised access only#","Configure an access warning banner.","Secure management","configuration",2],
  ["config.service-timestamps-log","global","service timestamps log datetime msec","Add date, time and milliseconds to log messages.","Monitoring services","configuration",2],
  ["config.service-timestamps-debug","global","service timestamps debug datetime msec","Add date, time and milliseconds to debug messages.","Monitoring services","configuration",2],
  ["config.logging-host","global","logging host 192.0.2.50","Send syslog messages to 192.0.2.50.","Monitoring services","configuration"],
  ["config.logging-trap","global","logging trap warnings","Send warning-level and more severe syslog messages.","Monitoring services","configuration",2],
  ["config.logging-buffered","global","logging buffered 16384 warnings","Buffer warning-level log messages locally.","Monitoring services","configuration",2],
  ["config.ntp-server","global","ntp server 192.0.2.20 prefer","Configure the preferred NTP server.","Monitoring services","configuration",2],
  ["config.ntp-master","global","ntp master 3","Make the simulator an NTP master at stratum 3.","Monitoring services","configuration",2],
  ["config.snmp-community","global","snmp-server community <community-value> ro","Configure a supplied read-only SNMP community in the simulator.","Monitoring services","configuration",2],
  ["config.snmp-location","global","snmp-server location London-Lab","Configure the SNMP location string.","Monitoring services","configuration"],
  ["config.snmp-contact","global","snmp-server contact network-team@example.com","Configure the SNMP contact string.","Monitoring services","configuration"],
  ["config.cdp-run","global","cdp run","Enable CDP globally.","Neighbour discovery","configuration"],
  ["config.lldp-run","global","lldp run","Enable LLDP globally.","Neighbour discovery","configuration"],
  ["config.ip-routing","global","ip routing","Enable IPv4 routing on a multilayer switch.","Routing","configuration"],
  ["config.default-gateway","global","ip default-gateway 192.0.2.254","Set a default gateway on a Layer 2 switch.","Routing","configuration"],
  ["route.floating","global","ip route 0.0.0.0 0.0.0.0 198.51.100.254 200","Configure a floating default route.","Routing","configuration",3],
  ["config.ipv6-routing","global","ipv6 unicast-routing","Enable IPv6 packet forwarding.","IPv6","configuration"],
  ["route.ipv6-default","global","ipv6 route ::/0 2001:db8:1::fe","Configure an IPv6 default route.","IPv6","configuration",2],
  ["nav.line-console","global","line console 0","Enter console line configuration.","CLI navigation","navigation"],
  ["nav.line-vty","global","line vty 0 4","Enter VTY line configuration for lines 0 through 4.","CLI navigation","navigation"],
  ["nav.vlan-20","global","vlan 20","Create VLAN 20 and enter VLAN configuration.","VLANs","navigation"],
  ["nav.vlan-99","global","vlan 99","Create VLAN 99 and enter VLAN configuration.","VLANs","navigation"],
  ["nav.acl-standard","global","ip access-list standard MGMT","Create named standard ACL MGMT.","Access control","navigation",2],
  ["nav.acl-extended","global","ip access-list extended WEB-IN","Create named extended ACL WEB-IN.","Access control","navigation",2],
  ["nav.dhcp-users","global","ip dhcp pool USERS","Create DHCP pool USERS.","DHCP","navigation",2],
  ["dhcp.exclude","global","ip dhcp excluded-address 192.0.2.1 192.0.2.20","Exclude the first twenty addresses from DHCP.","DHCP","configuration",2],
  ["config.nat-pat","global","ip nat inside source list 1 interface GigabitEthernet0/0 overload","Configure PAT using the outside interface address.","NAT","configuration",3],
  ["config.nat-static","global","ip nat inside source static 192.0.2.10 198.51.100.10","Configure a one-to-one static NAT mapping.","NAT","configuration",2],
  ["config.acl-standard","global","access-list 1 permit 192.0.2.0 0.0.0.255","Permit the inside subnet in standard ACL 1.","Access control","configuration",2],
  ["config.stp-mode","global","spanning-tree mode rapid-pvst","Use Rapid PVST+.","Spanning Tree","configuration",2],
  ["config.stp-root-primary","global","spanning-tree vlan 20 root primary","Make this switch the primary root for VLAN 20.","Spanning Tree","configuration",2],
  ["config.stp-root-secondary","global","spanning-tree vlan 20 root secondary","Make this switch the secondary root for VLAN 20.","Spanning Tree","configuration",2],
  ["config.dhcp-snooping","global","ip dhcp snooping","Enable DHCP snooping globally.","Switch security","configuration",2],
  ["config.dhcp-snooping-vlan","global","ip dhcp snooping vlan 20","Enable DHCP snooping for VLAN 20.","Switch security","configuration",2],
  ["config.arp-inspection-vlan","global","ip arp inspection vlan 20","Enable Dynamic ARP Inspection for VLAN 20.","Switch security","configuration",2],

  ["interface.ipv6-address","interface","ipv6 address 2001:db8:1::1/64","Assign an IPv6 address to the selected interface.","IPv6","configuration",2],
  ["interface.ipv6-enable","interface","ipv6 enable","Enable IPv6 processing and link-local addressing.","IPv6","configuration"],
  ["interface.helper","interface","ip helper-address 192.0.2.50","Relay UDP services to the DHCP server.","DHCP","configuration",2],
  ["interface.nat-inside","interface","ip nat inside","Mark the selected interface as NAT inside.","NAT","configuration"],
  ["interface.nat-outside","interface","ip nat outside","Mark the selected interface as NAT outside.","NAT","configuration"],
  ["interface.trunk","interface","switchport mode trunk","Set static trunk mode.","VLANs","configuration"],
  ["interface.trunk-native","interface","switchport trunk native vlan 99","Set VLAN 99 as the native VLAN.","VLANs","configuration",2],
  ["interface.trunk-allowed","interface","switchport trunk allowed vlan 10,20,99","Allow VLANs 10, 20 and 99 on the trunk.","VLANs","configuration",2],
  ["interface.voice-vlan","interface","switchport voice vlan 30","Assign voice VLAN 30.","VLANs","configuration",2],
  ["interface.portfast","interface","spanning-tree portfast","Enable PortFast on an edge port.","Spanning Tree","configuration"],
  ["interface.bpduguard","interface","spanning-tree bpduguard enable","Enable BPDU Guard on an edge port.","Spanning Tree","configuration",2],
  ["interface.rootguard","interface","spanning-tree guard root","Enable Root Guard.","Spanning Tree","configuration",2],
  ["interface.lacp-active","interface","channel-group 1 mode active","Join LACP port-channel 1 in active mode.","EtherChannel","configuration",2],
  ["interface.lacp-passive","interface","channel-group 1 mode passive","Join LACP port-channel 1 in passive mode.","EtherChannel","configuration",2],
  ["interface.pagp-desirable","interface","channel-group 1 mode desirable","Join PAgP channel 1 in desirable mode.","EtherChannel","configuration",2],
  ["interface.etherchannel-on","interface","channel-group 1 mode on","Join static EtherChannel 1.","EtherChannel","configuration",2],
  ["interface.cdp-disable","interface","no cdp enable","Disable CDP on the selected interface.","Neighbour discovery","configuration"],
  ["interface.lldp-transmit","interface","lldp transmit","Enable LLDP transmission.","Neighbour discovery","configuration"],
  ["interface.lldp-receive","interface","lldp receive","Enable LLDP reception.","Neighbour discovery","configuration"],
  ["interface.ospf-area","interface","ip ospf 10 area 0","Enable OSPF process 10 in area 0 on the interface.","OSPF","configuration",2],
  ["interface.ospf-cost","interface","ip ospf cost 50","Set the OSPF interface cost to 50.","OSPF","configuration",2],
  ["interface.ospf-priority","interface","ip ospf priority 0","Prevent the interface from becoming DR or BDR.","OSPF","configuration",3],
  ["interface.acl-in","interface","ip access-group WEB-IN in","Apply IPv4 ACL WEB-IN inbound.","Access control","configuration",2],
  ["interface.acl-out","interface","ip access-group WEB-IN out","Apply IPv4 ACL WEB-IN outbound.","Access control","configuration",2],
  ["interface.ipv6-acl-in","interface","ipv6 traffic-filter V6-IN in","Apply IPv6 ACL V6-IN inbound.","Access control","configuration",3],
  ["interface.port-security","interface","switchport port-security","Enable port security.","Switch security","configuration"],
  ["interface.port-security-max","interface","switchport port-security maximum 2","Allow at most two secure MAC addresses.","Switch security","configuration",2],
  ["interface.port-security-sticky","interface","switchport port-security mac-address sticky","Learn secure MAC addresses dynamically.","Switch security","configuration",2],
  ["interface.port-security-restrict","interface","switchport port-security violation restrict","Use restrict mode for port-security violations.","Switch security","configuration",2],
  ["interface.dhcp-trust","interface","ip dhcp snooping trust","Trust DHCP messages on this interface.","Switch security","configuration",2],
  ["interface.arp-trust","interface","ip arp inspection trust","Trust ARP messages on this interface.","Switch security","configuration",2],
  ["interface.hsrp-ip","interface","standby 10 ip 192.0.2.254","Configure the HSRP virtual IPv4 address.","First-hop redundancy","configuration",2],
  ["interface.hsrp-priority","interface","standby 10 priority 110","Set HSRP priority to 110.","First-hop redundancy","configuration",2],
  ["interface.hsrp-preempt","interface","standby 10 preempt","Allow the higher-priority HSRP router to retake active state.","First-hop redundancy","configuration",2],

  ["line.login-local","line","login local","Authenticate line access using the local user database.","Secure management","configuration"],
  ["line.transport-ssh","line","transport input ssh","Permit SSH but not Telnet on VTY lines.","Secure management","configuration"],
  ["line.exec-timeout","line","exec-timeout 10 0","Disconnect idle sessions after ten minutes.","Secure management","configuration",2],
  ["line.logging-sync","line","logging synchronous","Redraw command input after console messages.","CLI and system","configuration"],
  ["line.history-size","line","history size 50","Retain fifty commands in line history.","CLI and system","configuration"],
  ["nav.exit-line","line","exit","Leave line configuration mode.","CLI navigation","navigation"],
  ["nav.end-line","line","end","Return from line configuration to Privileged EXEC.","CLI navigation","navigation"],

  ["vlan.name-users","vlan","name USERS","Name the selected VLAN USERS.","VLANs","configuration"],
  ["vlan.name-management","vlan","name MANAGEMENT","Name the selected VLAN MANAGEMENT.","VLANs","configuration"],
  ["vlan.state-active","vlan","state active","Set the selected VLAN active.","VLANs","configuration",2],
  ["nav.exit-vlan","vlan","exit","Leave VLAN configuration mode.","CLI navigation","navigation"],
  ["nav.end-vlan","vlan","end","Return from VLAN configuration to Privileged EXEC.","CLI navigation","navigation"],

  ["router.router-id","router","router-id 192.0.2.1","Set the OSPF router ID.","OSPF","configuration",2],
  ["router.passive-default","router","passive-interface default","Make all OSPF interfaces passive by default.","OSPF","configuration",2],
  ["router.no-passive","router","no passive-interface GigabitEthernet0/0","Permit OSPF hellos on GigabitEthernet0/0.","OSPF","configuration",2],
  ["router.reference-bandwidth","router","auto-cost reference-bandwidth 10000","Use 10 Gbps as the OSPF reference bandwidth.","OSPF","configuration",3],
  ["router.default-originate","router","default-information originate","Advertise an existing default route into OSPF.","OSPF","configuration",2],
  ["router.maximum-paths","router","maximum-paths 4","Allow four equal-cost OSPF paths.","OSPF","configuration",2],

  ["acl.standard-permit","acl","permit 192.0.2.0 0.0.0.255","Permit the 192.0.2.0/24 source network.","Access control","configuration",2],
  ["acl.standard-deny","acl","deny host 198.51.100.10","Deny source host 198.51.100.10.","Access control","configuration",2],
  ["acl.extended-https","acl","permit tcp 192.0.2.0 0.0.0.255 host 198.51.100.10 eq 443","Permit HTTPS from the inside subnet to the web server.","Access control","configuration",3],
  ["acl.extended-dns","acl","permit udp 192.0.2.0 0.0.0.255 host 192.0.2.53 eq 53","Permit DNS queries to the DNS server.","Access control","configuration",3],
  ["acl.extended-icmp","acl","permit icmp any any echo","Permit ICMP echo requests.","Access control","configuration",2],
  ["acl.deny-any","acl","deny ip any any log","Deny and log all remaining IPv4 traffic.","Access control","configuration",2],
  ["nav.exit-acl","acl","exit","Leave named ACL configuration mode.","CLI navigation","navigation"],
  ["nav.end-acl","acl","end","Return from ACL configuration to Privileged EXEC.","CLI navigation","navigation"],

  ["dhcp.network","dhcp","network 192.0.2.0 255.255.255.0","Define the DHCP pool subnet.","DHCP","configuration"],
  ["dhcp.default-router","dhcp","default-router 192.0.2.254","Set the DHCP default gateway.","DHCP","configuration"],
  ["dhcp.dns-server","dhcp","dns-server 192.0.2.53","Set the DHCP DNS server.","DHCP","configuration"],
  ["dhcp.domain-name","dhcp","domain-name lab.example","Set the DHCP domain name.","DHCP","configuration"],
  ["dhcp.lease","dhcp","lease 7","Set a seven-day DHCP lease.","DHCP","configuration",2],
  ["nav.exit-dhcp","dhcp","exit","Leave DHCP pool configuration mode.","CLI navigation","navigation"],
  ["nav.end-dhcp","dhcp","end","Return from DHCP pool configuration to Privileged EXEC.","CLI navigation","navigation"],
];

export const expandedCommands: Command[] = rows.map(([
  id, mode, canonical, objective, topic, kind, difficulty = 1,
]) => ({
  id,
  mode,
  canonical,
  objective,
  explanation: objective,
  topic,
  kind,
  difficulty,
}));
