import type { CliContext } from "./engine.ts";

export type LabId = "router-foundation" | "switch-foundation";
export type LabPhase = "access" | "identity" | "security" | "services" | "interfaces" | "verification";
export type LabContext = CliContext;

export interface LabContentStep {
  id: string;
  conceptId: string;
  phase: LabPhase;
  context: LabContext;
  command: string;
  task: string;
  why: string;
  hint1: string;
  hint2: string;
  effect: string;
  verify: string;
  interpretation: string;
  commonFailure: string;
  recovery: string;
  nextContext?: LabContext;
  nextHostname?: "R1" | "SW1";
  output?: readonly string[];
  sensitiveArgumentNames?: readonly string[];
}

export interface LabContentDefinition {
  id: LabId;
  number: 2 | 3;
  title: string;
  summary: string;
  deviceProfile: "router-ios-xe" | "catalyst-l2";
  initialHostname: "Router" | "Switch";
  stages: readonly LabPhase[];
  steps: readonly LabContentStep[];
}

type StepOptions = Partial<Pick<LabContentStep,
  "hint1" | "hint2" | "interpretation" | "commonFailure" | "nextContext" | "nextHostname" | "output" | "sensitiveArgumentNames"
>>;

const firstKeyword = (command: string): string => command.trim().split(/\s+/u)[0] ?? "relevant";
const withoutPasteableCommand = (value: string, command: string): string => value.replace(
  new RegExp(command.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&"), "igu"),
  "the requested operation",
);

const defaultHint2 = (context: LabContext, command: string, task: string, why: string): string => {
  const family = firstKeyword(command);
  if (/\b(?:secret|key|password)\b/iu.test(command)) {
    return `At the ${context} prompt, use the ${family} family and enter the supplied case-sensitive training value only when requested.`;
  }
  if (/^(?:show|ping|ssh|traceroute|dir)\b/iu.test(command)) {
    return `At the ${context} prompt, use the ${family} inspection or test family to answer this one question: ${task}`;
  }
  if (/^(?:exit|end|enable|disable|configure|interface|line|router|vlan|radius|aaa group|ip access-list|ip dhcp pool)\b/iu.test(command)) {
    return `At the ${context} prompt, use the ${family} navigation family for “${task}” The next scope matters because ${why.charAt(0).toLocaleLowerCase("en-GB")}${why.slice(1)}`;
  }
  return `At the ${context} prompt, use the ${family} configuration family and supply only the target or value named here: ${task}`;
};

const defaultInterpretation = (task: string, effect: string, verify: string): string =>
  `Expected cause and effect: ${effect} Evidence for “${task}”: ${verify}`;

const defaultCommonFailure = (
  phase: LabPhase,
  task: string,
  effect: string,
  recovery: string,
): string => {
  if (phase === "verification") {
    return `Read-only output is not success by itself. If it does not prove “${effect}”, keep the task open and investigate the disagreeing field.`;
  }
  if (/^(?:Return|Move|Enter|Open|Select)/u.test(task)) {
    return `For “${task}”, a changed prompt proves only this scope: ${effect} It does not perform the next feature change or save earlier running configuration. If the scope was wrong: ${recovery}`;
  }
  return `Do not continue merely because IOS accepted the line. Verify “${effect}”; if the wrong object changed, follow this narrow recovery: ${recovery}`;
};

const step = (
  id: string,
  phase: LabPhase,
  context: LabContext,
  command: string,
  task: string,
  why: string,
  effect: string,
  verify: string,
  recovery: string,
  options: StepOptions = {},
): LabContentStep => ({
  id,
  conceptId: `lab.${id}`,
  phase,
  context,
  command,
  task,
  why,
  hint1: options.hint1 ?? withoutPasteableCommand(why, command),
  hint2: options.hint2 ?? defaultHint2(context, command, task, why),
  effect,
  verify,
  interpretation: options.interpretation ?? defaultInterpretation(task, effect, verify),
  commonFailure: options.commonFailure ?? defaultCommonFailure(phase, task, effect, recovery),
  recovery,
  ...(options.nextContext ? { nextContext: options.nextContext } : {}),
  ...(options.nextHostname ? { nextHostname: options.nextHostname } : {}),
  ...(options.output ? { output: options.output } : {}),
  ...(options.sensitiveArgumentNames ? { sensitiveArgumentNames: options.sensitiveArgumentNames } : {}),
});

const seededSecret = (purpose: "local" | "radius", seed: number): string => {
  const prefix = purpose === "local" ? "LocalLab" : "RadiusLab";
  return `${prefix}-${1_000 + (Math.abs(Math.trunc(seed)) % 8_000)}!`;
};

const saveOutput = ["Destination filename [startup-config]?", "Building configuration...", "[OK]"] as const;

const identityAndSsh = (
  hostname: "R1" | "SW1",
  localSecret: string,
  useAaaMethod: boolean,
): LabContentStep[] => [
  step("enable", "access", "user", "enable", "Move to Privileged EXEC.", "The restricted User EXEC prompt cannot enter device configuration.", "The prompt changes from > to # without changing configuration.", "Confirm that the prompt ends in #.", "Use disable to return to User EXEC.", { nextContext: "privileged", hint2: "Use the EXEC command that raises privilege; it begins with en." }),
  step("configure-terminal", "access", "privileged", "configure terminal", "Enter Global Configuration.", "Device-wide settings are changed from the (config)# prompt.", "The prompt changes to (config)# and later commands affect running configuration.", "Confirm the full prompt before entering a feature command.", "Use end to return to Privileged EXEC.", { nextContext: "global", hint2: "Use the terminal as the configuration source." }),
  step("hostname", "identity", "global", `hostname ${hostname}`, `Set the hostname to ${hostname}.`, "A short, unambiguous hostname makes prompts, logs and fault records easier to correlate.", `The device prompt begins with ${hostname} immediately.`, `Confirm the next prompt begins ${hostname}.`, "Reapply the documented hostname if the change was unintended.", { nextHostname: hostname, hint2: "Use the hostname command family followed by the supplied name." }),
  step("enable-secret", "security", "global", "enable secret Str0ngEnable!", "Protect Privileged EXEC with the supplied secret.", "The enable secret protects the privilege boundary and is preferred to the older enable password form.", "A protected enable-secret setting is recorded; the plaintext value is redacted from history and output.", "Keep a recovery session and test enable from a separate simulated session.", "Set and test a replacement before removing this control.", { sensitiveArgumentNames: ["secret"], hint2: "Use the enable command family with the secret form and the case-sensitive supplied value.", commonFailure: "IOS keywords ignore case, but the supplied secret value must match case exactly." }),
  step("local-admin", "security", "global", `username localadmin privilege 15 secret ${localSecret}`, "Create the fictional local break-glass administrator.", "A tested local account preserves emergency access when central authentication is unavailable.", "The local user exists with Privileged EXEC access; its secret is never printed or persisted in plaintext terminal history.", "Use a separate simulated login to prove the account before relying on it.", "Create and test a replacement account before removing localadmin.", { sensitiveArgumentNames: ["secret"], hint2: "Use username, the supplied name, privilege 15 and the secret form.", commonFailure: "A fallback account is useful only if its line method permits local authentication and it has been tested." }),
  step("password-encryption", "security", "global", "service password-encryption", "Obscure supported legacy plaintext-style passwords.", "Type 7 obfuscation reduces casual exposure but does not provide strong cryptographic protection.", "Supported legacy password fields are obscured; secret-based settings remain the preferred control.", "Inspect sanitised running configuration and distinguish secret hashes from reversible legacy fields.", "Remove the service only under policy; existing encoded values can remain encoded.", { hint2: "Use the global service whose name ends in password-encryption.", commonFailure: "Do not describe Type 7 as secure encryption or a replacement for secret-based commands." }),
  step("domain-name", "security", "global", "ip domain name lab.example", "Set the reserved lab domain name.", "IOS combines hostname and domain information when it creates the SSH server identity.", "The device has the fictional lab.example domain required by this training profile.", "Inspect the sanitised domain line before generating keys.", "Plan SSH key replacement before changing or removing the domain.", { hint2: "Use the global ip domain name command family and the reserved domain shown." }),
  step("rsa-key", "security", "global", "crypto key generate rsa modulus 2048", "Generate the simulated SSH RSA key.", "The SSH server needs a device key for identity and encrypted session establishment.", "The simulator records a 2048-bit RSA key capability without generating or storing real key material.", "Use show crypto key metadata on a compatible isolated lab image; never copy a generated private key.", "A real key zeroise interrupts SSH, so replace keys through an approved recovery path.", { hint2: "Use the crypto key generation family, select RSA and supply the stated modulus." }),
  step("ssh-version", "security", "global", "ip ssh version 2", "Require SSH version 2.", "SSHv2 is the expected encrypted remote-management protocol for the declared training platform.", "The simulated SSH service accepts version 2 and rejects legacy version 1 negotiation.", "Use show ip ssh and read the configured server version.", "Restore the approved version before closing a recovery session.", { hint2: "Use the global ip ssh version setting with the required version." }),
  step("vty-lines", "security", "global", "line vty 0 4", "Open the first five VTY lines.", "VTY line scope controls inbound terminal sessions rather than the whole device.", "The prompt changes to (config-line)# for lines 0 through 4.", "Confirm the line prompt and later inspect every VTY range supported by a real target.", "Use exit to leave line scope; undo individual settings with their targeted no forms.", { nextContext: "line", hint2: "Use the line command family, the VTY type and the supplied range." }),
  step("vty-login", "security", "line", useAaaMethod ? "login authentication default" : "login local", useAaaMethod ? "Apply the default AAA login method." : "Use the local user database for VTY login.", useAaaMethod ? "A method list has no effect on these VTY lines until the lines reference it." : "The fictional local account must be referenced before it can authenticate SSH sessions.", useAaaMethod ? "Inbound VTY login now uses RADIUS first with the configured local fallback." : "Inbound VTY login checks the local user database.", "Test a separate simulated SSH session before closing the current recovery session.", "Apply a tested replacement method before removing this line control.", { hint2: useAaaMethod ? "Use the line login authentication command with the named default method." : "Use the line login command with the local database option." }),
  step("vty-ssh-only", "security", "line", "transport input ssh", "Permit SSH and reject inbound Telnet.", "SSH encrypts credentials and session data; Telnet does not.", "The VTY range accepts inbound SSH only.", "Inspect the line section and test SSH while confirming Telnet is rejected.", "Temporarily broaden transport only within an isolated, approved recovery plan.", { hint2: "Use the line transport input setting with only the secure protocol." }),
  step("vty-timeout", "security", "line", "exec-timeout 10 0", "Set a ten-minute idle timeout.", "Idle administrative sessions should not remain open indefinitely.", "Inactive VTY sessions close after ten minutes and zero additional seconds.", "Inspect the VTY line configuration and test with a safe shortened lab interval if required.", "Restore the approved timeout before ending the recovery session.", { hint2: "Use exec-timeout with minutes first and seconds second." }),
  step("leave-vty", "security", "line", "exit", "Return to Global Configuration.", "The SSH line policy is complete and the next feature belongs to global scope.", "The prompt moves back one level to (config)# without undoing VTY changes.", "Confirm the full prompt before configuring another service.", "Re-enter with line vty 0 4 if another line setting is required.", { nextContext: "global" }),
];

export const createRouterFoundationContent = (seed = 1): LabContentDefinition => {
  const localSecret = seededSecret("local", seed);
  const radiusSecret = seededSecret("radius", seed);
  const steps: LabContentStep[] = [
    ...identityAndSsh("R1", localSecret, true).slice(0, 6),
    step("aaa-new-model", "security", "global", "aaa new-model", "Enable the AAA policy framework.", "AAA separates authentication and authorisation policy from individual access lines.", "The device can now use named central and local method lists.", "Keep the current recovery session open while the rest of AAA is built and tested.", "Use a protected recovery path before broadly removing AAA."),
    step("radius-server", "security", "global", "radius server RAD1", "Open the fictional RADIUS server profile.", "A named profile keeps the central server address and shared secret together.", "The prompt changes to the RADIUS server subcontext for RAD1.", "Confirm (config-radius-server)# before entering address or key settings.", "Remove method and group references before deleting the server profile.", { nextContext: "radius" }),
    step("radius-address", "security", "radius", "address ipv4 198.51.100.20 auth-port 1812 acct-port 1813", "Set the RADIUS documentation address and ports.", "The router needs a reachable server endpoint for authentication and accounting requests.", "RAD1 uses a reserved documentation address and the stated standard lab ports.", "Later verify IP reachability and simulated AAA server state separately.", "Use the exact no address form before replacing the endpoint.", { hint2: "Use address ipv4, then the supplied address, authentication port and accounting port." }),
    step("radius-key", "security", "radius", `key ${radiusSecret}`, "Set the fictional RADIUS shared secret.", "The network device and RADIUS service must hold the same case-sensitive shared secret.", "RAD1 has a redacted training key; no real packet or external service is contacted.", "A mismatched key appears as authentication failure despite IP reachability.", "Rotate both ends together; never remove the old key before the replacement path is ready.", { sensitiveArgumentNames: ["key"], hint2: "Use the key command followed by the supplied case-sensitive training value." }),
    step("leave-radius", "security", "radius", "exit", "Return to Global Configuration.", "The server endpoint is complete; group membership is configured globally.", "The prompt returns to (config)# without removing RAD1.", "Read the prompt before starting the group configuration.", "Re-enter with radius server RAD1.", { nextContext: "global" }),
    step("radius-group", "security", "global", "aaa group server radius RAD-GRP", "Create the RADIUS server group.", "A server group lets the policy reference a logical service rather than one endpoint.", "The prompt enters the AAA RADIUS server-group context for RAD-GRP.", "Confirm the server-group prompt before adding a member.", "Remove method-list references before deleting the group.", { nextContext: "aaa-group" }),
    step("radius-group-member", "security", "aaa-group", "server name RAD1", "Add RAD1 to the RADIUS group.", "A group definition is inert until it contains a named server profile.", "RAD-GRP now contains RAD1 as its simulated central authentication server.", "Inspect the AAA server-group state and confirm the named member.", "Use no server name RAD1 only after a replacement server is available."),
    step("leave-radius-group", "security", "aaa-group", "exit", "Return to Global Configuration.", "The group is ready for login and EXEC authorisation method lists.", "The prompt returns to (config)# and preserves group membership.", "Confirm the prompt before defining the method lists.", "Re-enter with aaa group server radius RAD-GRP.", { nextContext: "global" }),
    step("aaa-login", "security", "global", "aaa authentication login default group RAD-GRP local", "Use RADIUS login with local fallback.", "Central identity is preferred, while a tested local account protects access during server unavailability.", "The default login method tries RAD-GRP and then the local database when the server is unavailable.", "Test central success, server timeout with local success and explicit central rejection separately.", "Apply a known-good replacement method before removing this list.", { commonFailure: "Local fallback normally follows server unavailability; it must not be described as bypassing an explicit central rejection." }),
    step("aaa-exec-authorisation", "security", "global", "aaa authorization exec default group RAD-GRP local", "Authorise EXEC through RADIUS with local fallback.", "Authentication proves identity; EXEC authorisation decides whether an authenticated user may start an EXEC shell.", "The default EXEC authorisation list uses RAD-GRP and then local data during server unavailability.", "Use a separate simulated session and confirm both login and EXEC creation.", "Apply and test a replacement before removing authorisation."),
    ...identityAndSsh("R1", localSecret, true).slice(6),
    step("lan-interface", "interfaces", "global", "interface GigabitEthernet0/0/1", "Open the routed LAN interface.", "The LAN address, description and administrative state belong to one physical interface scope.", "GigabitEthernet0/0/1 becomes the selected interface and the prompt changes to (config-if)#.", "Confirm the selected interface in the prompt-independent simulator state.", "Use exit to leave the interface without removing its settings.", { nextContext: "interface" }),
    step("lan-description", "interfaces", "interface", "description USER LAN", "Describe the user LAN interface.", "A clear purpose label shortens remote troubleshooting and change review.", "The selected interface has the generic USER LAN description.", "Use show interfaces description and correlate the exact port.", "Use no description to remove only this label."),
    step("lan-address", "interfaces", "interface", "ip address 192.168.10.1 255.255.255.0", "Assign the private LAN gateway address.", "Hosts in 192.168.10.0/24 need a reachable router address on their own subnet.", "The interface owns 192.168.10.1/24; a connected route can appear when the interface is operational.", "Use show ip interface brief and show ip route connected.", "Move dependent services before using no ip address."),
    step("lan-enable", "interfaces", "interface", "no shutdown", "Administratively enable the LAN interface.", "A correctly addressed router interface cannot forward while configuration keeps it shut.", "The administrative block is removed; the seeded peer lets the lab interface reach up/up.", "Read both Status and Protocol in show ip interface brief.", "Use shutdown during an approved service withdrawal.", { commonFailure: "No shutdown does not repair cabling or a remote-side fault on a real device." }),
    step("leave-lan", "interfaces", "interface", "exit", "Return to Global Configuration.", "DHCP and static routing are configured outside the physical interface subcontext.", "The prompt returns to (config)# while the LAN state remains active.", "Confirm the prompt before entering a global DHCP command.", "Re-enter the LAN interface to alter its state.", { nextContext: "global" }),
    step("dhcp-exclusion", "services", "global", "ip dhcp excluded-address 192.168.10.1 192.168.10.20", "Reserve the infrastructure address range.", "The gateway and fixed infrastructure addresses must not be handed to dynamic clients.", "Addresses .1 through .20 are excluded from the USERS pool allocation range.", "Inspect the running DHCP exclusions and the pool's available count.", "Use the exact no form if the documented reservation range changes."),
    step("dhcp-pool", "services", "global", "ip dhcp pool USERS", "Open the USERS DHCP pool.", "A named pool groups the client network and supplied options.", "The prompt changes to (dhcp-config)# for the USERS pool.", "Confirm the pool prompt before entering network or option statements.", "Remove the complete pool only after dependent clients are migrated.", { nextContext: "dhcp" }),
    step("dhcp-network", "services", "dhcp", "network 192.168.10.0 255.255.255.0", "Define the DHCP client subnet.", "The service must know which /24 network supplies addresses for this pool.", "USERS allocates from 192.168.10.0/24 outside the exclusion range.", "Use show ip dhcp pool and interpret the total and available addresses.", "Use the exact no network form before changing the subnet."),
    step("dhcp-gateway", "services", "dhcp", "default-router 192.168.10.1", "Supply the client default gateway.", "Clients need the router's on-subnet address to reach non-local destinations.", "Leases from USERS advertise 192.168.10.1 as the default router.", "Inspect a deterministic binding and its supplied options.", "Use the exact no default-router form before replacing the gateway."),
    step("dhcp-dns", "services", "dhcp", "dns-server 192.0.2.53", "Supply the fictional DNS resolver.", "DHCP clients need a resolver address for hostname lookups; the lab uses a documentation address only.", "USERS leases advertise 192.0.2.53 as their resolver.", "Inspect a test lease and distinguish DNS configuration from IP reachability.", "Use the exact no dns-server form before replacing the option."),
    step("leave-dhcp", "services", "dhcp", "exit", "Return to Global Configuration.", "The pool is complete and the default route belongs to global routing scope.", "The prompt returns to (config)# and retains the USERS pool.", "Confirm the prompt before entering the route.", "Re-enter with ip dhcp pool USERS.", { nextContext: "global" }),
    step("default-route", "interfaces", "global", "ip route 0.0.0.0 0.0.0.0 192.0.2.2", "Add the default route through the seeded WAN gateway.", "Unknown IPv4 destinations need an upstream next hop already reachable through the seeded WAN /30.", "A candidate default route points to 192.0.2.2; the connected WAN route resolves that next hop.", "Use show ip route and then test a documentation remote host with a known return path.", "Remove the exact route only after confirming an alternate path or planned outage."),
    step("end-configuration", "verification", "global", "end", "Return to Privileged EXEC for verification.", "Operational evidence is easiest to read from the # prompt after the change set is complete.", "The prompt returns to R1# without saving automatically.", "Confirm the full prompt and keep the running/startup distinction clear.", "Use configure terminal to return to global scope.", { nextContext: "privileged" }),
    step("verify-interfaces", "verification", "privileged", "show ip interface brief", "Verify routed interface addresses and state.", "A concise baseline exposes a missing address, administrative shutdown or line-protocol fault.", "The simulator emits state derived from the configured LAN and seeded WAN interfaces.", "Confirm both interfaces have their intended addresses and report up/up.", "This is read-only; correct the narrowest faulty interface setting.", { output: ["Interface              IP-Address      OK? Method Status                Protocol", "GigabitEthernet0/0/0   192.0.2.1       YES manual up                    up", "GigabitEthernet0/0/1   192.168.10.1    YES manual up                    up"], interpretation: "An assigned address does not prove health; Status and Protocol must also agree with the expected link state." }),
    step("verify-routes", "verification", "privileged", "show ip route", "Verify connected and default routes.", "The LAN and WAN connected routes must exist before the default next hop can be resolved.", "The routing table includes connected LAN/WAN prefixes and the static candidate default.", "Confirm 0.0.0.0/0 resolves through 192.0.2.2 and the LAN is connected.", "This is read-only; remove or replace only the incorrect route object.", { output: ["Gateway of last resort is 192.0.2.2 to network 0.0.0.0", "C 192.168.10.0/24 is directly connected, GigabitEthernet0/0/1", "C 192.0.2.0/30 is directly connected, GigabitEthernet0/0/0", "S* 0.0.0.0/0 [1/0] via 192.0.2.2"] }),
    step("verify-dhcp-pool", "verification", "privileged", "show ip dhcp pool", "Verify the DHCP pool and available range.", "A configured pool can still be unusable when its network or exclusions consume the wrong addresses.", "The USERS pool reports the /24 network and addresses available after the .1–.20 exclusion.", "Confirm the pool network, utilisation and excluded infrastructure range.", "This is read-only; correct the exact global or pool setting that disagrees.", { output: ["Pool USERS :", " Utilization mark (high/low) : 100 / 0", " Subnet size (first/next)    : 0 / 0", " Total addresses             : 254", " Leased addresses            : 1", " Excluded addresses          : 20"] }),
    step("verify-dhcp-binding", "verification", "privileged", "show ip dhcp binding", "Inspect the deterministic client binding.", "A binding proves the server selected a pool address for a simulated client; it does not prove every application works.", "One fictional client holds 192.168.10.21 with a bounded lab lease.", "Confirm the address lies outside the exclusion range and inside the /24.", "This is read-only; release or clear bindings only in a dedicated safe exercise.", { output: ["IP address       Client-ID              Lease expiration        Type", "192.168.10.21   01aa.bbcc.ddee.ff       Jul 14 2026 10:00 AM    Automatic"] }),
    step("verify-aaa-ready", "verification", "privileged", "show aaa servers", "Confirm the central server is ready for a login test.", "Testing fallback before proving the normal central path can hide a server, group or shared-secret fault.", "RAD1 reports UP only when its endpoint and case-sensitive shared credential are configured and it is enabled.", "Read the server name, documentation address and UP state from the simulator output.", "This is read-only; correct the specific server or group dependency before testing a login."),
    step("verify-central-login", "verification", "privileged", "ssh -l centraladmin 192.0.2.1", "Prove central authentication in a separate simulated login.", "The preferred RADIUS method must work normally before an outage and fallback test mean anything.", "A separate SSH session reports that RAD1 accepted the fictional centraladmin identity.", "Confirm central RADIUS acceptance and encrypted session establishment are reported separately.", "Close only the test session; retain the original recovery session before simulating an outage."),
    step("enter-radius-outage-config", "access", "privileged", "configure terminal", "Enter Global Configuration for the outage exercise.", "The RADIUS server's administrative state is changed from its named configuration object.", "The prompt changes to R1(config)# without altering the already verified central path.", "Confirm the (config)# prompt before selecting RAD1.", "Use end to abandon navigation without changing the server.", { nextContext: "global" }),
    step("open-radius-outage", "security", "global", "radius server RAD1", "Open the configured RAD1 server profile.", "The deliberate outage must target the named training server without deleting its endpoint or shared credential.", "The prompt changes to the RADIUS server subcontext for the existing RAD1 object.", "Confirm the server name and RADIUS subcontext before changing administrative state.", "Use exit to leave the profile without changing it.", { nextContext: "radius" }),
    step("simulate-radius-outage", "security", "radius", "shutdown", "Administratively disable RAD1 for the fallback test.", "A controlled no-response state proves method-list fallback without pretending that central rejection permits bypass.", "RAD1 retains its configuration but changes from UP to administratively disabled.", "Return to Privileged EXEC and inspect the server state before attempting local login.", "Use no shutdown in the same server profile to restore normal central authentication."),
    step("end-radius-outage", "access", "radius", "end", "Return to Privileged EXEC after disabling RAD1.", "The outage state must be verified from operational output before testing the fallback account.", "The prompt returns directly to R1# while RAD1 remains disabled in running configuration.", "Confirm the # prompt; this action does not save the outage state.", "Re-enter the RAD1 profile and use no shutdown to restore it.", { nextContext: "privileged" }),
    step("verify-aaa", "verification", "privileged", "show aaa servers", "Confirm RAD1 is unavailable for the fallback test.", "Local fallback is appropriate for server unavailability, not for an explicit central rejection.", "RAD1 reports DEAD because the isolated exercise deliberately disabled it; its endpoint and credential remain configured.", "Read the DEAD reason and distinguish administrative outage from missing configuration.", "Re-enable RAD1 with the targeted no form after the fallback test."),
    step("verify-fallback", "verification", "privileged", "ssh -l localadmin 192.0.2.1", "Prove local fallback in a separate simulated login.", "A configuration line is not evidence of recoverability; a second session must authenticate while RADIUS is unavailable.", "The simulator reports a RADIUS no-response result followed by local acceptance and an encrypted session.", "Confirm central timeout, local success and session establishment are stated separately.", "Close only the test session, then re-enable RAD1 and retest normal central authentication."),
    step("verify-ssh", "verification", "privileged", "show ip ssh", "Verify the SSH server configuration.", "Server configuration and active SSH sessions are different forms of evidence.", "The simulator reports SSH version 2 and the configured idle/session controls.", "Confirm version 2; use show ssh separately for active sessions.", "This is read-only; correct the relevant global or VTY setting.", { output: ["SSH Enabled - version 2.0", "Authentication timeout: 120 secs; Authentication retries: 3"] }),
    step("test-lan", "verification", "privileged", "ping 192.168.10.21", "Test the simulated DHCP client path.", "A successful on-subnet test checks the LAN interface, address, ARP and client return path together.", "Five replies return from the deterministic client binding.", "Read the 100 percent success rate and correlate it with the connected route.", "This is read-only; diagnose state rather than undoing the probe.", { output: ["!!!!!", "Success rate is 100 percent (5/5)"] }),
    step("test-remote", "verification", "privileged", "ping 203.0.113.10", "Test the seeded remote path.", "A remote probe validates the connected WAN next hop, default route and deterministic remote return path.", "Five replies return through 192.0.2.2 and the static default route.", "Confirm the selected route and return path rather than treating ping alone as complete proof.", "This is read-only; remove no configuration because of the probe itself.", { output: ["!!!!!", "Success rate is 100 percent (5/5)", "Forward path: 0.0.0.0/0 via 192.0.2.2; simulated return path present"] }),
    step("save", "verification", "privileged", "copy running-config startup-config", "Save the verified router configuration.", "Startup configuration should receive only a change set that has passed access, service and forwarding checks.", "After the interactive default destination is accepted, startup storage becomes a snapshot of running state.", "Compare critical startup sections with running state after [OK].", "Correct and verify running state, then save again or restore a known-good snapshot.", { output: saveOutput }),
    step("verify-startup", "verification", "privileged", "show startup-config", "Verify the saved router configuration.", "A successful copy message is not a substitute for checking that the intended sections are present in startup state.", "The simulator emits a redacted, bounded startup snapshot.", "Confirm hostname, AAA method references, SSH, LAN, DHCP and route sections without exposing secrets.", "This is read-only; restore or resave a verified snapshot if it differs.", { output: ["! redacted startup configuration", "hostname R1", "aaa new-model", "interface GigabitEthernet0/0/1", " ip address 192.168.10.1 255.255.255.0", "ip route 0.0.0.0 0.0.0.0 192.0.2.2"] }),
  ];
  return {
    id: "router-foundation",
    number: 2,
    title: "Build and verify a secure branch router",
    summary: "Identity, protected access, RADIUS with local fallback, SSH, routed LAN, DHCP, default routing, verification and save.",
    deviceProfile: "router-ios-xe",
    initialHostname: "Router",
    stages: ["access", "identity", "security", "services", "interfaces", "verification"],
    steps,
  };
};

export const createSwitchFoundationContent = (seed = 1): LabContentDefinition => {
  const localSecret = seededSecret("local", seed);
  const steps: LabContentStep[] = [
    ...identityAndSsh("SW1", localSecret, false),
    step("vlan10", "services", "global", "vlan 10", "Create the data VLAN.", "VLAN 10 provides the data broadcast domain before access ports can use it.", "VLAN 10 exists and the prompt enters VLAN Configuration.", "Use show vlan brief after all three VLANs are named.", "Use no vlan 10 only after moving dependent ports.", { nextContext: "vlan" }),
    step("vlan10-name", "services", "vlan", "name DATA", "Name VLAN 10 DATA.", "A generic functional label helps operators identify the broadcast domain without exposing a site name.", "VLAN 10 has the DATA label.", "Confirm ID 10 and name DATA in show vlan brief.", "Use no name or apply the approved replacement label."),
    step("leave-vlan10", "services", "vlan", "exit", "Return to Global Configuration.", "The next VLAN is created from global scope.", "The prompt returns to (config)# and retains VLAN 10.", "Confirm the prompt before creating VLAN 20.", "Re-enter with vlan 10.", { nextContext: "global" }),
    step("vlan20", "services", "global", "vlan 20", "Create the voice VLAN.", "A separate voice VLAN lets phones receive voice-specific Layer 2 treatment and addressing policy.", "VLAN 20 exists and the prompt enters VLAN Configuration.", "Use show vlan brief after naming it.", "Move voice ports before deleting the VLAN.", { nextContext: "vlan" }),
    step("vlan20-name", "services", "vlan", "name VOICE", "Name VLAN 20 VOICE.", "The label distinguishes voice membership from the data and management domains.", "VLAN 20 has the VOICE label.", "Confirm ID 20 and name VOICE.", "Use no name or the approved replacement label."),
    step("leave-vlan20", "services", "vlan", "exit", "Return to Global Configuration.", "The management VLAN is a separate configuration object.", "The prompt returns to (config)#.", "Confirm the prompt before creating VLAN 99.", "Re-enter with vlan 20.", { nextContext: "global" }),
    step("vlan99", "services", "global", "vlan 99", "Create the management VLAN.", "The switch SVI needs its VLAN to exist and have active Layer 2 membership.", "VLAN 99 exists and the prompt enters VLAN Configuration.", "Correlate the VLAN with the later SVI and trunk allowance.", "Migrate management before deleting this VLAN.", { nextContext: "vlan" }),
    step("vlan99-name", "services", "vlan", "name MANAGEMENT", "Name VLAN 99 MANAGEMENT.", "A functional label makes the management path obvious in verification output.", "VLAN 99 has the MANAGEMENT label.", "Confirm ID 99 and name MANAGEMENT.", "Use no name or the approved replacement label."),
    step("end-for-vlan-check", "verification", "vlan", "end", "Return to Privileged EXEC for the VLAN check.", "The VLAN table is an operational verification view.", "The prompt returns directly to SW1# without saving.", "Confirm the # prompt before the show command.", "Use configure terminal to resume the build.", { nextContext: "privileged" }),
    step("verify-vlans", "verification", "privileged", "show vlan brief", "Verify all three VLANs and names.", "Creating ports before checking VLAN existence can hide a simple dependency fault.", "The table contains DATA 10, VOICE 20 and MANAGEMENT 99 in active state.", "Read ID, Name and Status for all three rows.", "This is read-only; correct the exact VLAN object that disagrees.", { output: ["VLAN Name                             Status", "10   DATA                             active", "20   VOICE                            active", "99   MANAGEMENT                       active"] }),
    step("resume-configuration", "access", "privileged", "configure terminal", "Return to Global Configuration.", "The remaining edge, uplink and management settings change running configuration.", "The prompt returns to SW1(config)#.", "Confirm the prompt before selecting a range.", "Use end to return to Privileged EXEC.", { nextContext: "global" }),
    step("data-range", "interfaces", "global", "interface range FastEthernet1/0/1 - 4", "Select the data-only edge ports.", "A declared range applies one consistent edge policy to four existing FastEthernet interfaces.", "The prompt enters Interface Range Configuration for ports 1 through 4.", "Confirm the expanded member list before applying state.", "Use exit; targeted follow-up can correct one member if required.", { nextContext: "interface-range", hint2: "Use interface range, the first port, a spaced hyphen and the last port number." }),
    step("data-access-mode", "interfaces", "interface-range", "switchport mode access", "Set the data range explicitly to access mode.", "Explicit access mode prevents dynamic trunk negotiation from changing the edge role.", "All four selected ports operate as static access ports.", "Use show interfaces switchport on a representative member and inspect every range member.", "Restore the approved prior mode during a planned change."),
    step("data-vlan", "interfaces", "interface-range", "switchport access vlan 10", "Assign data VLAN 10 to the range.", "Untagged workstation traffic must enter the intended data broadcast domain.", "All selected ports use VLAN 10 for access traffic.", "Confirm the access VLAN on every member.", "Move endpoints before changing the VLAN."),
    step("data-portfast", "interfaces", "interface-range", "spanning-tree portfast", "Enable PortFast on the edge range.", "Known endpoint ports can enter forwarding quickly without waiting through normal STP transitions.", "PortFast is enabled on each selected edge port.", "Confirm the ports are true edge links and inspect spanning-tree state.", "Remove PortFast before connecting a switch or shared Layer 2 segment.", { commonFailure: "PortFast does not disable spanning tree and must not be enabled blindly on switch-to-switch links." }),
    step("data-bpduguard", "interfaces", "interface-range", "spanning-tree bpduguard enable", "Enable BPDU Guard on the edge range.", "A received BPDU on an endpoint port can indicate an accidental or unauthorised switch connection.", "Each selected port protects the edge boundary by err-disabling on unexpected BPDUs.", "Inspect spanning-tree and err-disable evidence after a controlled lab BPDU.", "Remove the cause before recovering an err-disabled port."),
    step("data-port-security", "interfaces", "interface-range", "switchport port-security", "Enable port security on the data range.", "Port security constrains learned source MAC addresses on the declared endpoint boundary.", "Port security is active on each selected access port.", "Use show port-security and inspect each member's enabled state.", "Disable only after assessing the trust boundary and learned addresses."),
    step("data-port-security-max", "interfaces", "interface-range", "switchport port-security maximum 2", "Permit at most two learned MAC addresses.", "The lab permits a bounded endpoint case without leaving an unlimited learned-address surface.", "Each selected port accepts no more than two secure MAC addresses.", "Inspect maximum, current and violation counters per port.", "Change the maximum only after documenting the endpoint design."),
    step("data-port-security-restrict", "interfaces", "interface-range", "switchport port-security violation restrict", "Restrict traffic after a security violation.", "Restrict drops frames from violating sources and increments counters without shutting the whole port.", "Violation mode is restrict on all selected ports.", "Generate only controlled lab violations and read the counters.", "Correct the endpoint or secure-address plan before clearing evidence."),
    step("data-enable", "interfaces", "interface-range", "no shutdown", "Administratively enable the data range.", "The configured edge policy cannot serve endpoints while the ports remain disabled.", "Administrative shutdown is removed from ports 1 through 4.", "Use show interfaces status and inspect every member.", "Use shutdown during an approved service withdrawal."),
    step("leave-data-range", "interfaces", "interface-range", "exit", "Return to Global Configuration.", "The phone-and-workstation range uses a related but distinct voice policy.", "The prompt returns to (config)#.", "Confirm the prompt before opening the second range.", "Re-enter the first range if it needs a correction.", { nextContext: "global" }),
    step("voice-range", "interfaces", "global", "interface range FastEthernet1/0/5 - 8", "Select the phone-and-workstation ports.", "A second range makes the voice VLAN policy explicit rather than overloading data-only ports.", "The prompt enters Interface Range Configuration for ports 5 through 8.", "Confirm the expanded member list.", "Use exit to leave the range.", { nextContext: "interface-range" }),
    step("voice-access-mode", "interfaces", "interface-range", "switchport mode access", "Set the voice range to access mode.", "The access role carries untagged workstation data while the phone can use the separate voice VLAN.", "All selected phone-facing ports are static access ports.", "Inspect switchport mode on every member.", "Restore the approved prior mode if the port role changes."),
    step("voice-data-vlan", "interfaces", "interface-range", "switchport access vlan 10", "Assign data VLAN 10 to the voice range.", "A workstation attached through a phone normally sends untagged data into the data VLAN.", "Untagged traffic on ports 5 through 8 belongs to VLAN 10.", "Confirm the access VLAN separately from the voice VLAN.", "Move endpoints before changing it."),
    step("voice-vlan", "interfaces", "interface-range", "switchport voice vlan 20", "Advertise voice VLAN 20 to the phones.", "The phone can tag voice traffic into VLAN 20 while forwarding workstation data in VLAN 10.", "Ports 5 through 8 use VLAN 20 for supported voice endpoints.", "Inspect access and voice VLAN fields together.", "Remove or replace the voice VLAN only after phone provisioning is updated."),
    step("voice-portfast", "interfaces", "interface-range", "spanning-tree portfast", "Enable PortFast on the phone range.", "Phones and attached workstations are endpoint devices in this declared topology.", "PortFast is enabled across the second edge range.", "Confirm no downstream switch is connected.", "Remove PortFast if the topology changes."),
    step("voice-bpduguard", "interfaces", "interface-range", "spanning-tree bpduguard enable", "Protect the phone range with BPDU Guard.", "An endpoint-facing port should not receive switch control BPDUs.", "Unexpected BPDUs trigger the simulated protection on every selected port.", "Inspect spanning-tree and err-disable state after a controlled test.", "Remove the cause before recovering the port."),
    step("voice-port-security", "interfaces", "interface-range", "switchport port-security", "Enable port security on the phone range.", "The combined phone-and-workstation edge still needs a bounded learned-address policy.", "Port security is active on ports 5 through 8.", "Inspect state and counters per interface.", "Disable only after reviewing the edge trust boundary."),
    step("voice-port-security-max", "interfaces", "interface-range", "switchport port-security maximum 2", "Permit the phone-and-workstation MAC pair.", "A phone plus a workstation behind it can legitimately present two source MAC addresses on one switch port.", "The maximum is two secure MAC addresses per selected port.", "Confirm current addresses do not exceed the planned pair.", "Raise the limit only for a documented endpoint design.", { interpretation: "The phone and attached workstation are separate Ethernet devices, so one physical access port can learn both source MAC addresses." }),
    step("voice-port-security-restrict", "interfaces", "interface-range", "switchport port-security violation restrict", "Restrict unplanned source MAC addresses.", "Restrict preserves the authorised endpoint session while dropping and counting violating sources.", "The second range uses restrict violation mode.", "Inspect violation counters after a controlled lab event.", "Correct the endpoint or learned-address policy before clearing evidence."),
    step("voice-enable", "interfaces", "interface-range", "no shutdown", "Administratively enable the phone range.", "The voice and data policy cannot serve endpoints while configuration keeps the ports disabled.", "Ports 5 through 8 leave administrative shutdown.", "Use show interfaces status and inspect every member.", "Use shutdown during an approved outage."),
    step("leave-voice-range", "interfaces", "interface-range", "exit", "Return to Global Configuration.", "The uplink bundle uses separate high-speed interfaces and LACP.", "The prompt returns to (config)#.", "Confirm the prompt before opening the uplink range.", "Re-enter the range for a targeted correction.", { nextContext: "global" }),
    step("uplink-range", "interfaces", "global", "interface range TenGigabitEthernet1/1/1 - 2", "Select the two 10 Gb uplinks.", "Two declared high-speed interfaces will form one logical LACP bundle.", "The prompt enters Interface Range Configuration for both TenGigabitEthernet members.", "Confirm both exact member interfaces before changing them.", "Use exit and correct members individually if required.", { nextContext: "interface-range" }),
    step("uplink-lacp", "interfaces", "interface-range", "channel-group 1 mode active", "Add both uplinks to LACP channel group 1.", "LACP active mode sends negotiation frames and avoids a silent static bundle mismatch.", "Both physical members belong to Port-channel1 with active LACP intent.", "Use show etherchannel summary and verify member flags.", "Remove members from the channel group before repurposing them."),
    step("leave-uplink-range", "interfaces", "interface-range", "exit", "Return to Global Configuration.", "Trunk policy is applied to the logical Port-channel rather than repeated on members.", "The prompt returns to (config)#.", "Confirm the prompt before opening Port-channel1.", "Re-enter the member range if membership changes.", { nextContext: "global" }),
    step("port-channel", "interfaces", "global", "interface Port-channel1", "Open the logical LACP interface.", "A logical bundle presents one configuration and forwarding object to spanning tree and trunking.", "Port-channel1 becomes selected and the prompt enters Interface Configuration.", "Confirm the selected logical interface.", "Use exit without removing the bundle.", { nextContext: "interface" }),
    step("port-channel-trunk", "interfaces", "interface", "switchport mode trunk", "Set Port-channel1 to trunk mode.", "The uplink must carry multiple VLANs towards the upstream switch.", "The logical bundle operates as a static trunk.", "Use show interfaces trunk and show etherchannel summary.", "Coordinate both ends before changing trunk mode."),
    step("port-channel-vlans", "interfaces", "interface", "switchport trunk allowed vlan 10,20,99", "Allow only the three lab VLANs.", "An explicit allowed list constrains the Layer 2 scope and makes verification deterministic.", "Port-channel1 carries VLANs 10, 20 and 99.", "Confirm every required VLAN is allowed and forwarding.", "Restore the approved previous list rather than blindly allowing every VLAN."),
    step("port-channel-enable", "interfaces", "interface", "no shutdown", "Administratively enable Port-channel1.", "The logical interface must be enabled before the bundle can forward VLAN traffic.", "Administrative shutdown is removed from the Port-channel.", "Correlate Port-channel and physical-member state.", "Use shutdown only during a coordinated uplink outage."),
    step("leave-port-channel", "interfaces", "interface", "exit", "Return to Global Configuration.", "Management SVI state belongs to the VLAN logical interface.", "The prompt returns to (config)#.", "Confirm the prompt before opening Vlan99.", "Re-enter Port-channel1 for trunk corrections.", { nextContext: "global" }),
    step("management-svi", "interfaces", "global", "interface Vlan99", "Open the management SVI.", "The SVI gives this Layer 2 switch an IP endpoint for SSH and monitoring.", "Vlan99 becomes selected and the prompt enters Interface Configuration.", "Confirm VLAN 99 exists and is active on the trunk.", "Use exit without removing the SVI.", { nextContext: "interface" }),
    step("management-address", "interfaces", "interface", "ip address 192.0.2.2 255.255.255.0", "Assign the documentation-only management address.", "A stable lab address gives administrators a deterministic switch management endpoint without copying a real site subnet.", "Vlan99 owns 192.0.2.2/24.", "Use show ip interface brief and confirm the address.", "Migrate management before removing or changing it."),
    step("management-enable", "interfaces", "interface", "no shutdown", "Administratively enable the management SVI.", "An SVI can be configured correctly yet remain administratively disabled.", "The administrative block is removed; its line protocol depends on active VLAN 99 membership.", "Correlate SVI state with VLAN and trunk state.", "Use shutdown only with another management path."),
    step("leave-management-svi", "interfaces", "interface", "exit", "Return to Global Configuration.", "A Layer 2 default gateway is configured globally when IP routing is disabled.", "The prompt returns to (config)#.", "Confirm the prompt before setting the gateway.", "Re-enter Vlan99 for SVI corrections.", { nextContext: "global" }),
    step("management-gateway", "interfaces", "global", "ip default-gateway 192.0.2.1", "Set the Layer 2 management gateway.", "The switch needs an on-subnet router for replies to off-subnet management stations when IP routing is disabled.", "Off-subnet management traffic uses 192.0.2.1.", "Ping the gateway, then test from an approved remote management subnet.", "Use the exact no form or apply the approved replacement gateway.", { commonFailure: "On a multilayer switch with IP routing enabled, routing replaces the Layer 2 ip default-gateway behaviour." }),
    step("unused-range", "interfaces", "global", "interface range FastEthernet1/0/9 - 24", "Select every unused access port.", "Unused physical access ports should have an explicit safe state rather than remain available by accident.", "The prompt enters Interface Range Configuration for ports 9 through 24.", "Confirm the expanded range excludes all required endpoint ports.", "Use exit before correcting an accidental range selection.", { nextContext: "interface-range" }),
    step("unused-description", "interfaces", "interface-range", "description UNUSED", "Label the unused access range.", "A consistent label helps later operators distinguish intentional shutdown from an unexplained fault.", "Every selected unused port has the generic UNUSED description.", "Use show interfaces description and inspect the full range.", "Use no description only when repurposing a port."),
    step("unused-shutdown", "interfaces", "interface-range", "shutdown", "Administratively disable unused ports.", "A disabled unused port reduces accidental attachment and narrows the exposed Layer 2 surface.", "Ports 9 through 24 report administratively down.", "Use show interfaces status and confirm required ports were not included.", "Repurpose one port through an approved configuration and no shutdown."),
    step("end-switch-configuration", "verification", "interface-range", "end", "Return to Privileged EXEC for verification.", "The complete switching state now needs Layer 1, VLAN, spanning-tree, security and bundle evidence.", "The prompt returns to SW1# without saving automatically.", "Confirm the prompt before the show sequence.", "Use configure terminal for a targeted correction.", { nextContext: "privileged" }),
    step("verify-interface-status", "verification", "privileged", "show interfaces status", "Check physical and logical interface status.", "The concise port table quickly exposes an unexpected disabled, unconnected or wrongly assigned interface.", "The simulator emits endpoint, unused and 10 Gb uplink state from the configured ranges.", "Confirm required ports are enabled and unused ports are disabled.", "This is read-only; correct only the range or member that disagrees."),
    step("verify-vlan-membership", "verification", "privileged", "show vlan brief", "Check data, voice and management VLANs.", "VLAN existence and access membership are prerequisites for endpoint and SVI behaviour.", "VLANs 10, 20 and 99 remain active with their generic names.", "Confirm VLAN IDs, names and access-port membership.", "This is read-only; correct the exact VLAN or switchport setting."),
    step("verify-trunk", "verification", "privileged", "show interfaces trunk", "Check the Port-channel trunk VLANs.", "A bundle can be up while required VLANs are absent from its allowed or forwarding list.", "Port-channel1 is a trunk carrying VLANs 10, 20 and 99.", "Read mode, allowed VLANs and forwarding VLANs together.", "This is read-only; coordinate both ends before altering trunk state."),
    step("verify-spanning-tree", "verification", "privileged", "show spanning-tree", "Check spanning-tree roles and edge state.", "A forwarding topology must remain loop-free while endpoint ports receive their intended edge treatment.", "The simulator reports Port-channel1 as the upstream path and endpoint ranges as protected edge ports.", "Confirm root information, port roles and the absence of an inconsistent state.", "This is read-only; do not change STP from one unexplained line."),
    step("verify-port-security", "verification", "privileged", "show port-security", "Check port-security limits and violations.", "A configured policy is useful only when enabled on the intended interfaces with the planned maximum and violation mode.", "Ports 1 through 8 report enabled, maximum 2 and restrict mode with zero seeded violations.", "Inspect current, maximum and violation counters per interface.", "This is read-only; investigate before clearing evidence."),
    step("verify-etherchannel", "verification", "privileged", "show etherchannel summary", "Check LACP bundle membership.", "Both physical members must be compatible and bundled for Port-channel1 to provide the intended path.", "The summary reports a Layer 2 Port-channel with both TenGigabitEthernet members bundled.", "Interpret protocol and member flags rather than relying only on the group number.", "This is read-only; correct compatibility before removing members."),
    step("test-management-gateway", "verification", "privileged", "ping 192.0.2.1", "Test the documentation-only management gateway.", "A successful probe checks the SVI, active management VLAN, trunk and seeded gateway return path together.", "Five deterministic replies return through Vlan99 and Port-channel1.", "Read the success rate and named path; ping alone does not prove SSH policy.", "This is read-only; diagnose the specific dependency if it fails.", { output: ["!!!!!", "Success rate is 100 percent (5/5)", "Path: Vlan99 -> Port-channel1 -> 192.0.2.1"] }),
    step("save-switch", "verification", "privileged", "copy running-config startup-config", "Save the verified switch configuration.", "Only verified identity, edge, uplink and management state should become the restart baseline.", "After destination confirmation, startup storage becomes a snapshot of running state.", "Compare the critical startup sections after [OK].", "Correct and verify running state, then save again or restore a known-good snapshot.", { output: saveOutput }),
    step("verify-switch-startup", "verification", "privileged", "show startup-config", "Verify the saved switch configuration.", "A copy-complete message does not prove that every required section is present in startup storage.", "The simulator emits a bounded redacted startup snapshot.", "Confirm hostname, SSH, VLAN, ranges, Port-channel, SVI and gateway sections without exposing secrets.", "This is read-only; restore or resave a verified snapshot if it differs."),
  ];
  return {
    id: "switch-foundation",
    number: 3,
    title: "Build and verify a secure access switch",
    summary: "Identity, SSH, VLANs, protected edge ranges, voice, LACP trunking, management, unused-port shutdown, verification and save.",
    deviceProfile: "catalyst-l2",
    initialHostname: "Switch",
    stages: ["access", "identity", "security", "services", "interfaces", "verification"],
    steps,
  };
};

export const createLabContent = (id: LabId, seed = 1): LabContentDefinition =>
  id === "router-foundation"
    ? createRouterFoundationContent(seed)
    : createSwitchFoundationContent(seed);

export const labContentDefinitions = [
  createRouterFoundationContent(),
  createSwitchFoundationContent(),
] as const;
